// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SGIP.Infrastructure.Persistence;

#nullable disable

namespace SGIP.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260625053553_UpdateSchemaToSnakeCase")]
    partial class UpdateSchemaToSnakeCase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SGIP.Domain.Entities.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("interest_rate");

                    b.Property<int>("LoanType")
                        .HasColumnType("integer")
                        .HasColumnName("loan_type");

                    b.Property<decimal>("MonthlyPayment")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monthly_payment");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Term")
                        .HasColumnType("integer")
                        .HasColumnName("term");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_loans_user_id");

                    b.ToTable("loans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a3b84f92-12c4-4d81-8b1a-9f4a2153c390"),
                            Amount = 1000.00m,
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            InterestRate = 0.20m,
                            LoanType = 0,
                            MonthlyPayment = 344.41m,
                            Status = 3,
                            Term = 3,
                            UpdatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "USR-001"
                        });
                });

            modelBuilder.Entity("SGIP.Domain.Entities.PaymentSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<decimal>("Interest")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("interest");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uuid")
                        .HasColumnName("loan_id");

                    b.Property<int>("PaymentNumber")
                        .HasColumnType("integer")
                        .HasColumnName("payment_number");

                    b.Property<decimal>("Principal")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("principal");

                    b.Property<decimal>("RemainingBalance")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("remaining_balance");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalPayment")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_payment");

                    b.HasKey("Id");

                    b.HasIndex("LoanId")
                        .HasDatabaseName("ix_payment_schedules_loan_id");

                    b.ToTable("payment_schedules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            DueDate = new DateTime(2026, 7, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 15.30m,
                            LoanId = new Guid("a3b84f92-12c4-4d81-8b1a-9f4a2153c390"),
                            PaymentNumber = 1,
                            Principal = 329.11m,
                            RemainingBalance = 670.89m,
                            Status = 0,
                            TotalPayment = 344.41m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            DueDate = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 10.26m,
                            LoanId = new Guid("a3b84f92-12c4-4d81-8b1a-9f4a2153c390"),
                            PaymentNumber = 2,
                            Principal = 334.15m,
                            RemainingBalance = 336.74m,
                            Status = 0,
                            TotalPayment = 344.41m
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            DueDate = new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 7.67m,
                            LoanId = new Guid("a3b84f92-12c4-4d81-8b1a-9f4a2153c390"),
                            PaymentNumber = 3,
                            Principal = 336.74m,
                            RemainingBalance = 0.00m,
                            Status = 0,
                            TotalPayment = 344.41m
                        });
                });

            modelBuilder.Entity("SGIP.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("LoanId")
                        .HasColumnType("uuid")
                        .HasColumnName("loan_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_transactions_idempotency_key");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("SGIP.Domain.Entities.PaymentSchedule", b =>
                {
                    b.HasOne("SGIP.Domain.Entities.Loan", "Loan")
                        .WithMany("PaymentSchedules")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("SGIP.Domain.Entities.Loan", b =>
                {
                    b.Navigation("PaymentSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
