// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SGIP.Infrastructure.Persistence;

#nullable disable

namespace SGIP.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260625080324_SeedDB")]
    partial class SeedDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SGIP.Domain.Entities.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("interest_rate");

                    b.Property<int>("LoanType")
                        .HasColumnType("integer")
                        .HasColumnName("loan_type");

                    b.Property<decimal>("MonthlyPayment")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monthly_payment");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Term")
                        .HasColumnType("integer")
                        .HasColumnName("term");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_loans_user_id");

                    b.ToTable("loans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a3b84f92-12c4-4d81-8b1a-9f4a2153c390"),
                            Amount = 1000.00m,
                            CreatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            InterestRate = 0.20m,
                            LoanType = 0,
                            MonthlyPayment = 344.41m,
                            Status = 3,
                            Term = 3,
                            UpdatedAt = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "USR-001"
                        },
                        new
                        {
                            Id = new Guid("b1c94f02-23d5-4e92-9c2b-af5b3264d401"),
                            Amount = 2000.00m,
                            CreatedAt = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            InterestRate = 0.20m,
                            LoanType = 0,
                            MonthlyPayment = 351.42m,
                            Status = 3,
                            Term = 6,
                            UpdatedAt = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "user-01"
                        },
                        new
                        {
                            Id = new Guid("c2d05f13-34e6-5fa3-ad3c-bf6c4375e512"),
                            Amount = 1800.00m,
                            CreatedAt = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            InterestRate = 0.20m,
                            LoanType = 1,
                            MonthlyPayment = 327.56m,
                            Status = 3,
                            Term = 6,
                            UpdatedAt = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = "user-02"
                        });
                });

            modelBuilder.Entity("SGIP.Domain.Entities.PaymentSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<decimal>("Interest")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("interest");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uuid")
                        .HasColumnName("loan_id");

                    b.Property<int>("PaymentNumber")
                        .HasColumnType("integer")
                        .HasColumnName("payment_number");

                    b.Property<decimal>("Principal")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("principal");

                    b.Property<decimal>("RemainingBalance")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("remaining_balance");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalPayment")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_payment");

                    b.HasKey("Id");

                    b.HasIndex("LoanId")
                        .HasDatabaseName("ix_payment_schedules_loan_id");

                    b.ToTable("payment_schedules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            DueDate = new DateTime(2026, 7, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 15.30m,
                            LoanId = new Guid("a3b84f92-12c4-4d81-8b1a-9f4a2153c390"),
                            PaymentNumber = 1,
                            Principal = 329.11m,
                            RemainingBalance = 670.89m,
                            Status = 0,
                            TotalPayment = 344.41m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            DueDate = new DateTime(2026, 8, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 10.26m,
                            LoanId = new Guid("a3b84f92-12c4-4d81-8b1a-9f4a2153c390"),
                            PaymentNumber = 2,
                            Principal = 334.15m,
                            RemainingBalance = 336.74m,
                            Status = 0,
                            TotalPayment = 344.41m
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            DueDate = new DateTime(2026, 9, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 7.67m,
                            LoanId = new Guid("a3b84f92-12c4-4d81-8b1a-9f4a2153c390"),
                            PaymentNumber = 3,
                            Principal = 336.74m,
                            RemainingBalance = 0.00m,
                            Status = 0,
                            TotalPayment = 344.41m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444441"),
                            DueDate = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 30.62m,
                            LoanId = new Guid("b1c94f02-23d5-4e92-9c2b-af5b3264d401"),
                            PaymentNumber = 1,
                            Principal = 320.80m,
                            RemainingBalance = 1679.20m,
                            Status = 0,
                            TotalPayment = 351.42m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444442"),
                            DueDate = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 25.71m,
                            LoanId = new Guid("b1c94f02-23d5-4e92-9c2b-af5b3264d401"),
                            PaymentNumber = 2,
                            Principal = 325.71m,
                            RemainingBalance = 1353.49m,
                            Status = 0,
                            TotalPayment = 351.42m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444443"),
                            DueDate = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 20.73m,
                            LoanId = new Guid("b1c94f02-23d5-4e92-9c2b-af5b3264d401"),
                            PaymentNumber = 3,
                            Principal = 330.69m,
                            RemainingBalance = 1022.80m,
                            Status = 0,
                            TotalPayment = 351.42m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            DueDate = new DateTime(2026, 10, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 15.66m,
                            LoanId = new Guid("b1c94f02-23d5-4e92-9c2b-af5b3264d401"),
                            PaymentNumber = 4,
                            Principal = 335.76m,
                            RemainingBalance = 687.04m,
                            Status = 0,
                            TotalPayment = 351.42m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444445"),
                            DueDate = new DateTime(2026, 11, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 10.52m,
                            LoanId = new Guid("b1c94f02-23d5-4e92-9c2b-af5b3264d401"),
                            PaymentNumber = 5,
                            Principal = 340.90m,
                            RemainingBalance = 346.14m,
                            Status = 0,
                            TotalPayment = 351.42m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444446"),
                            DueDate = new DateTime(2026, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 5.30m,
                            LoanId = new Guid("b1c94f02-23d5-4e92-9c2b-af5b3264d401"),
                            PaymentNumber = 6,
                            Principal = 346.14m,
                            RemainingBalance = 0.00m,
                            Status = 0,
                            TotalPayment = 351.44m
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555551"),
                            DueDate = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 27.56m,
                            LoanId = new Guid("c2d05f13-34e6-5fa3-ad3c-bf6c4375e512"),
                            PaymentNumber = 1,
                            Principal = 300.00m,
                            RemainingBalance = 1500.00m,
                            Status = 0,
                            TotalPayment = 327.56m
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555552"),
                            DueDate = new DateTime(2026, 8, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 22.96m,
                            LoanId = new Guid("c2d05f13-34e6-5fa3-ad3c-bf6c4375e512"),
                            PaymentNumber = 2,
                            Principal = 300.00m,
                            RemainingBalance = 1200.00m,
                            Status = 0,
                            TotalPayment = 322.96m
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555553"),
                            DueDate = new DateTime(2026, 9, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 18.37m,
                            LoanId = new Guid("c2d05f13-34e6-5fa3-ad3c-bf6c4375e512"),
                            PaymentNumber = 3,
                            Principal = 300.00m,
                            RemainingBalance = 900.00m,
                            Status = 0,
                            TotalPayment = 318.37m
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555554"),
                            DueDate = new DateTime(2026, 10, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 13.78m,
                            LoanId = new Guid("c2d05f13-34e6-5fa3-ad3c-bf6c4375e512"),
                            PaymentNumber = 4,
                            Principal = 300.00m,
                            RemainingBalance = 600.00m,
                            Status = 0,
                            TotalPayment = 313.78m
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            DueDate = new DateTime(2026, 11, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 9.19m,
                            LoanId = new Guid("c2d05f13-34e6-5fa3-ad3c-bf6c4375e512"),
                            PaymentNumber = 5,
                            Principal = 300.00m,
                            RemainingBalance = 300.00m,
                            Status = 0,
                            TotalPayment = 309.19m
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555556"),
                            DueDate = new DateTime(2026, 12, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Interest = 4.59m,
                            LoanId = new Guid("c2d05f13-34e6-5fa3-ad3c-bf6c4375e512"),
                            PaymentNumber = 6,
                            Principal = 300.00m,
                            RemainingBalance = 0.00m,
                            Status = 0,
                            TotalPayment = 304.59m
                        });
                });

            modelBuilder.Entity("SGIP.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("LoanId")
                        .HasColumnType("uuid")
                        .HasColumnName("loan_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_transactions_idempotency_key");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("SGIP.Domain.Entities.PaymentSchedule", b =>
                {
                    b.HasOne("SGIP.Domain.Entities.Loan", "Loan")
                        .WithMany("PaymentSchedules")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("SGIP.Domain.Entities.Loan", b =>
                {
                    b.Navigation("PaymentSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
